marks = [82, 70, 91]
marks.append(95)
marks.remove(70)
print(len(marks))
print(marks.contains(91))
print(marks.index(91))
marks.sort()
print(marks.get(0))
marks.set(0, 75)
marks.reverse()
print(marks.pop())
marks.clear()
print(marks.length())
