text = "  Hello World Hello  "
print(len(text))
print(text.upper())
print(text.lower())
print(text.strip())
print("World" in text)
print(text.startswith("  Hello"))
print(text.endswith("  "))
print(text.replace("World", "Codex"))
print(text.substring(2, 7))
print(text.charAt(2))
print(text.find("Hello"))
print(text.rfind("Hello"))
print("".isEmpty())
print(text.equals("  Hello World Hello  "))
words = text.split(" ")
print(words[2])
print("ha".repeat(3))
print(text.reverse())
print("hello world".capitalize())
print("hello world".title())
print(text.count("Hello"))
