string text = "  Hello World Hello  ";
print(text.length());
print(text.toUpperCase());
print(text.toLowerCase());
print(text.trim());
print(text.contains("World"));
print(text.startsWith("  Hello"));
print(text.endsWith("  "));
print(text.replace("World", "Codex"));
print(text.substring(2, 7));
print(text.charAt(2));
print(text.indexOf("Hello"));
print(text.lastIndexOf("Hello"));
print("".isEmpty());
print(text.equals("  Hello World Hello  "));
words = text.split(" ");
print(words[2]);
print("ha".repeat(3));
print(text.reverse());
print("hello world".capitalize());
print("hello world".title());
print(text.count("Hello"));
